on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [created]

name: Build and Test

jobs:
  run_unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
